manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Si quieres más remotos personalizados, agrégalos aquí
    # - name: gpeye
    #   url-base: https://github.com/GPeye

  projects:
    - name: eyelash_sofle
      url: https://github.com/a741725193/zmk-sofle
      revision: main

    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-nice-oled
      url: https://github.com/mctechnology17/zmk-nice-oled
      revision: main
      path: modules/lib/zmk-nice-oled   # <- ruta recomendada para módulos extra

  self:
    path: boards
